kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - main
  ref:
    exclude:
      - refs/tags/*

steps:
  - name: Semantic Release
    image: node:18
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
    - yarn --frozen-lockfile
    - yarn semantic-release
   