kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - main
  ref:
    exclude:
      - refs/tags/*

steps:
  - name: Semantic Release
    image: node:18
    environment:
      NPM_REGISTRY_PROTO: https
      NPM_REGISTRY: verdaccio.nas.local.abbottland.io
      NPM_TOKEN:
        from_secret: NPM_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
    - yarn --frozen-lockfile
    - yarn semantic-release
   